version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
 
  discountdb:
    container_name: discountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  orderdb:
    container_name: orderdb
    environment:
        MSSQL_SA_PASSWORD: "Admin@12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1432:1433"

  rabbitmqgenerictech:
    container_name: rabbitmqgenerictech
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672" 

  pgadmin:
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=zakaria.bijoy12@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    volumes:
      - pgadmin_data:/root/.pgadmin
    ports:
      - "5050:80"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "ElasticConfiguration:Uri=http://elasticsearchgenerictech" 
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmqgenerictech:5672"
      - "ElasticConfiguration:Uri=http://elasticsearchgenerictech" 
    depends_on:
      - basketdb
      - rabbitmqgenerictech 
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234"
      - "ElasticConfiguration:Uri=http://elasticsearchgenerictech" 
    depends_on:
      - discountdb
    ports:
      - "8002:80"


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "ElasticConfiguration:Uri=http://elasticsearchgenerictech" 
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb; Database=OrderDb; User Id=sa; Password=Admin@12345678;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmqgenerictech:5672"
      - "ElasticConfiguration:Uri=http://elasticsearchgenerictech" 
    depends_on:
      - orderdb
      - rabbitmqgenerictech 
    ports:
      - "8004:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearchgenerictech" 
    depends_on:
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api 
    ports:
      - "8010:80"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "APISettings:CatalogUrl=http://catalog.api"
      - "APISettings:BasketUrl=http://basket.api"
      - "APISettings:OrderingUrl=http://ordering.api"
      - "ElasticConfiguration:Uri=http://elasticsearchgenerictech" 
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "8005:80"


  generictech.aspnetcorewebapp:
    container_name: generictech.aspnetcorewebapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "APISettings:GatewayAddress=http://ocelotapigw"
      - "ElasticConfiguration:Uri=http://elasticsearchgenerictech" 
    depends_on:
      - ocelotapigw
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "8006:80"

  elasticsearchgenerictech:
    container_name: elasticsearchgenerictech
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"  
    volumes:
      - elasticsearchgenerictech-data:/usr/share/elasticsearch/data

  kibanagenerictech:
    container_name: kibanagenerictech
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearchgenerictech
    depends_on:
      - elasticsearchgenerictech
    ports:
      - "5601:5601"

